services:
  backend:
    image: fajobi13/kubetasks-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - kubetasks-network

  frontend:
    image: fajobi13/kubetasks-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - kubetasks-network

networks:
  kubetasks-network:
    driver: bridge