services:
  backend:
    image: fajobi13/kubetasks-backend:latest
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/todos
    networks:
      - kubetasks-network

  frontend:
    image: fajobi13/kubetasks-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5001
    networks:
      - kubetasks-network


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kubetasks-network

volumes:
  postgres_data:
    driver: local

networks:
  kubetasks-network:
    driver: bridge