services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"  # Map to port 5001 instead of 5000
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"  # Avoid conflicts with port 3000
    depends_on:
      - backend