name: Python Tests and Deployment

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push backend image
      - name: Build and push backend
        working-directory: ./backend
        run: |
          docker build -t fajobi13/kubetasks-backend:latest .
          docker tag fajobi13/kubetasks-backend:latest fajobi13/kubetasks-backend:${{ github.sha }}
          docker push fajobi13/kubetasks-backend:latest
          docker push fajobi13/kubetasks-backend:${{ github.sha }}

      # Step 7: Build and push frontend image
      - name: Build and push frontend
        working-directory: ./frontend
        run: |
          docker build -t fajobi13/kubetasks-frontend:latest .
          docker tag fajobi13/kubetasks-frontend:latest fajobi13/kubetasks-frontend:${{ github.sha }}
          docker push fajobi13/kubetasks-frontend:latest
          docker push fajobi13/kubetasks-frontend:${{ github.sha }}

      # Step 8: Deploy to Kubernetes (optional, if using Kubernetes)
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f frontend-deployment.yaml


