name: Build and Push Docker Images

on:
  push:
    branches:
      - aces

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Backend Tests
        working-directory: ./backend
        run: pytest tests/

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push backend image
      - name: Build and push backend
        working-directory: ./backend
        run: |
          docker build -t fajobi13/kubetasks-backend:latest .
          docker tag fajobi13/kubetasks-backend:latest fajobi13/kubetasks-backend:${{ github.sha }}
          docker push fajobi13/kubetasks-backend:latest
          docker push fajobi13/kubetasks-backend:${{ github.sha }}

      # Step 4: Build and push frontend image
      - name: Build and push frontend
        working-directory: ./frontend
        run: |
          docker build -t fajobi13/kubetasks-frontend:latest .
          docker tag fajobi13/kubetasks-frontend:latest fajobi13/kubetasks-frontend:${{ github.sha }}
          docker push fajobi13/kubetasks-frontend:latest
          docker push fajobi13/kubetasks-frontend:${{ github.sha }}
